version: '3.3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 8089:8089
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf