version: '3.3'

services:

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 8089:8089
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  
  